# Generated by Django 5.0.1 on 2024-02-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soln", "0002_alter_healthfacilities_geom"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="healthfacilities",
            index=models.Index(fields=["geom"], name="geom_index"),
        ),
    ]
